#include "idlebstate.hpp"
#include "walkingbstate.hpp"
#include "ticketbstate.hpp"
#include "paintingbstate.hpp"
#include "crosswordbstate.hpp"
#include "sudokubstate.hpp"
#include "checkbstate.hpp"
#include "selfbstate.hpp"
